package com.yingyinqi.jasperreport.enums;

/**
 * @author: create by libin
 * @version: v1.0
 * @description: com.yingyinqi.jasperreport.enums
 * @date:2020/4/15
 */
public enum  MineTypeEnum {
    evy("evy","application/envoy"),
    fif("fif","application/fractals"),
    spl("spl","application/futuresplash"),
    hta("hta","application/hta"),
    acx("acx","application/internet-property-stream"),
    hqx("hqx","application/mac-binhex40"),
    doc("doc","application/msword"),
    dot("dot","application/msword"),
    bin("bin","application/octet-stream"),
    dms("dms","application/octet-stream"),
    exe("exe","application/octet-stream"),
    lha("lha","application/octet-stream"),
    lzh("lzh","application/octet-stream"),
    oda("oda","application/oda"),
    axs("axs","application/olescript"),
    pdf("pdf","application/pdf"),
    prf("prf","application/pics-rules"),
    p10("p10","application/pkcs10"),
    crl("crl","application/pkix-crl"),
    ai("ai","application/postscript"),
    eps("eps","application/postscript"),
    ps("ps","application/postscript"),
    rtf("rtf","application/rtf"),
    setpay("setpay","application/set-payment-initiation"),
    setreg("setreg","application/set-registration-initiation"),
    xla("xla","application/vnd.ms-excel"),
    xlc("xlc","application/vnd.ms-excel"),
    xlm("xlm","application/vnd.ms-excel"),
    xls("xls","application/vnd.ms-excel"),
    xlt("xlt","application/vnd.ms-excel"),
    xlw("xlw","application/vnd.ms-excel"),
    msg("msg","application/vnd.ms-outlook"),
    sst("sst","application/vnd.ms-pkicertstore"),
    cat("cat","application/vnd.ms-pkiseccat"),
    stl("stl","application/vnd.ms-pkistl"),
    pot("pot","application/vnd.ms-powerpoint"),
    pps("pps","application/vnd.ms-powerpoint"),
    ppt("ppt","application/vnd.ms-powerpoint"),
    mpp("mpp","application/vnd.ms-project"),
    wcm("wcm","application/vnd.ms-works"),
    wdb("wdb","application/vnd.ms-works"),
    wks("wks","application/vnd.ms-works"),
    wps("wps","application/vnd.ms-works"),
    hlp("hlp","application/winhlp"),
    bcpio("bcpio","application/x-bcpio"),
    cdf("cdf","application/x-cdf"),
    z("z","application/x-compress"),
    tgz("tgz","application/x-compressed"),
    cpio("cpio","application/x-cpio"),
    csh("csh","application/x-csh"),
    dcr("dcr","application/x-director"),
    dir("dir","application/x-director"),
    dxr("dxr","application/x-director"),
    dvi("dvi","application/x-dvi"),
    gtar("gtar","application/x-gtar"),
    gz("gz","application/x-gzip"),
    hdf("hdf","application/x-hdf"),
    ins("ins","application/x-internet-signup"),
    isp("isp","application/x-internet-signup"),
    iii("iii","application/x-iphone"),
    js("js","application/x-javascript"),
    latex("latex","application/x-latex"),
    mdb("mdb","application/x-msaccess"),
    crd("crd","application/x-mscardfile"),
    clp("clp","application/x-msclip"),
    dll("dll","application/x-msdownload"),
    m13("m13","application/x-msmediaview"),
    m14("m14","application/x-msmediaview"),
    mvb("mvb","application/x-msmediaview"),
    wmf("wmf","application/x-msmetafile"),
    mny("mny","application/x-msmoney"),
    pub("pub","application/x-mspublisher"),
    scd("scd","application/x-msschedule"),
    trm("trm","application/x-msterminal"),
    wri("wri","application/x-mswrite"),
    nc("nc","application/x-netcdf"),
    pma("pma","application/x-perfmon"),
    pmc("pmc","application/x-perfmon"),
    pml("pml","application/x-perfmon"),
    pmr("pmr","application/x-perfmon"),
    pmw("pmw","application/x-perfmon"),
    p12("p12","application/x-pkcs12"),
    pfx("pfx","application/x-pkcs12"),
    p7b("p7b","application/x-pkcs7-certificates"),
    spc("spc","application/x-pkcs7-certificates"),
    p7r("p7r","application/x-pkcs7-certreqresp"),
    p7c("p7c","application/x-pkcs7-mime"),
    p7m("p7m","application/x-pkcs7-mime"),
    p7s("p7s","application/x-pkcs7-signature"),
    sh("sh","application/x-sh"),
    shar("shar","application/x-shar"),
    swf("swf","application/x-shockwave-flash"),
    sit("sit","application/x-stuffit"),
    sv4cpio("sv4cpio","application/x-sv4cpio"),
    sv4crc("sv4crc","application/x-sv4crc"),
    tar("tar","application/x-tar"),
    tcl("tcl","application/x-tcl"),
    tex("tex","application/x-tex"),
    texi("texi","application/x-texinfo"),
    texinfo("texinfo","application/x-texinfo"),
    roff("roff","application/x-troff"),
    t("t","application/x-troff"),
    tr("tr","application/x-troff"),
    man("man","application/x-troff-man"),
    me("me","application/x-troff-me"),
    ms("ms","application/x-troff-ms"),
    ustar("ustar","application/x-ustar"),
    src("src","application/x-wais-source"),
    cer("cer","application/x-x509-ca-cert"),
    crt("crt","application/x-x509-ca-cert"),
    der("der","application/x-x509-ca-cert"),
    pko("pko","application/ynd.ms-pkipko"),
    zip("zip","application/zip"),
    au("au","audio/basic"),
    snd("snd","audio/basic"),
    mid("mid","audio/mid"),
    rmi("rmi","audio/mid"),
    mp3("mp3","audio/mpeg"),
    aif("aif","audio/x-aiff"),
    aifc("aifc","audio/x-aiff"),
    aiff("aiff","audio/x-aiff"),
    m3u("m3u","audio/x-mpegurl"),
    ra("ra","audio/x-pn-realaudio"),
    ram("ram","audio/x-pn-realaudio"),
    wav("wav","audio/x-wav"),
    bmp("bmp","image/bmp"),
    cod("cod","image/cis-cod"),
    gif("gif","image/gif"),
    ief("ief","image/ief"),
    jpe("jpe","image/jpeg"),
    jpeg("jpeg","image/jpeg"),
    jpg("jpg","image/jpeg"),
    jfif("jfif","image/pipeg"),
    svg("svg","image/svg+xml"),
    tif("tif","image/tiff"),
    tiff("tiff","image/tiff"),
    ras("ras","image/x-cmu-raster"),
    cmx("cmx","image/x-cmx"),
    ico("ico","image/x-icon"),
    pnm("pnm","image/x-portable-anymap"),
    pbm("pbm","image/x-portable-bitmap"),
    pgm("pgm","image/x-portable-graymap"),
    ppm("ppm","image/x-portable-pixmap"),
    rgb("rgb","image/x-rgb"),
    xbm("xbm","image/x-xbitmap"),
    xpm("xpm","image/x-xpixmap"),
    xwd("xwd","image/x-xwindowdump"),
    mht("mht","message/rfc822"),
    mhtml("mhtml","message/rfc822"),
    nws("nws","message/rfc822"),
    ss("ss","text/css"),
    htm("htm","text/html"),
    html("html","text/html"),
    stm("stm","text/html"),
    uls("uls","text/iuls"),
    bas("bas","text/plain"),
    c("c","text/plain"),
    h("h","text/plain"),
    txt("txt","text/plain"),
    rtx("rtx","text/richtext"),
    sct("sct","text/scriptlet"),
    tsv("tsv","text/tab-separated-values"),
    htt("htt","text/webviewhtml"),
    htc("htc","text/x-component"),
    etx("etx","text/x-setext"),
    vcf("vcf","text/x-vcard"),
    mp2("mp2","video/mpeg"),
    mpa("mpa","video/mpeg"),
    mpe("mpe","video/mpeg"),
    mpeg("mpeg","video/mpeg"),
    mpg("mpg","video/mpeg"),
    mpv2("mpv2","video/mpeg"),
    mov("mov","video/quicktime"),
    qt("qt","video/quicktime"),
    lsf("lsf","video/x-la-asf"),
    lsx("lsx","video/x-la-asf"),
    asf("asf","video/x-ms-asf"),
    asr("asr","video/x-ms-asf"),
    asx("asx","video/x-ms-asf"),
    avi("avi","video/x-msvideo"),
    movie("movie","video/x-sgi-movie"),
    flr("flr","x-world/x-vrml"),
    vrml("vrml","x-world/x-vrml"),
    wrl("wrl","x-world/x-vrml"),
    wrz("wrz","x-world/x-vrml"),
    xaf("xaf","x-world/x-vrml"),
    xof("xof","x-world/x-vrml");
    private String name;
    private String mineType;
    MineTypeEnum(String name,String mineType) {
        this.name=name;
        this.mineType=mineType;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMineType() {
        return mineType;
    }

    public void setMineType(String mineType) {
        this.mineType = mineType;
    }
}
